from __future__ import annotations

from pathlib import Path

from scripts.benchmark_solver_modes import _build_row


def _payload(*, solver_metadata: dict[str, object], solver_status: str = "SOLVED_FEASIBLE") -> dict[str, object]:
    return {
        "solver_status": solver_status,
        "status": solver_status,
        "objective_value": 100.0,
        "solve_time_seconds": 1.5,
        "summary": {
            "trip_count_served": 1,
            "trip_count_unserved": 0,
            "vehicle_count_used": 1,
        },
        "canonical_solver_result": {
            "solver_status": solver_status,
            "objective_value": 100.0,
            "served_trip_ids": ["t1"],
            "unserved_trip_ids": [],
            "vehicle_paths": {"veh-1": ["t1"]},
            "incumbent_history": [
                {"iteration": 0, "objective_value": 100.0, "feasible": True, "wall_clock_sec": 0.0},
            ],
            "solver_metadata": solver_metadata,
        },
    }


def test_benchmark_solver_maturity_gates_main_vs_appendix() -> None:
    cases = [
        (
            "mode_milp_only",
            {
                "true_solver_family": "milp",
                "independent_implementation": True,
                "delegates_to": "none",
                "solver_display_name": "MILP",
                "solver_maturity": "core",
                "candidate_generation_mode": "exact_branch_and_cut",
                "evaluation_mode": "total_cost",
                "eligible_for_main_benchmark": True,
                "eligible_for_appendix_benchmark": False,
                "comparison_note": "Exact core solver; main benchmark candidate.",
                "fallback_applied": False,
                "fallback_reason": "none",
                "has_feasible_incumbent": True,
                "incumbent_count": 1,
                "warm_start_applied": True,
                "warm_start_source": "baseline_plan",
                "search_profile": {
                    "total_wall_clock_sec": 1.5,
                    "first_feasible_sec": 0.1,
                    "incumbent_updates": 1,
                    "evaluator_calls": 2,
                    "avg_evaluator_sec": 0.1,
                    "repair_calls": 0,
                    "avg_repair_sec": 0.0,
                    "exact_repair_calls": 0,
                    "avg_exact_repair_sec": 0.0,
                    "feasible_candidate_ratio": 1.0,
                    "rejected_candidate_ratio": 0.0,
                    "fallback_count": 0,
                },
            },
            "main",
            True,
        ),
        (
            "mode_alns_only",
            {
                "true_solver_family": "alns",
                "independent_implementation": True,
                "delegates_to": "none",
                "solver_display_name": "ALNS",
                "solver_maturity": "core",
                "candidate_generation_mode": "destroy_repair_local_search",
                "evaluation_mode": "total_cost",
                "eligible_for_main_benchmark": True,
                "eligible_for_appendix_benchmark": False,
                "comparison_note": "Core metaheuristic; main benchmark candidate.",
                "fallback_applied": False,
                "fallback_reason": "none",
                "has_feasible_incumbent": True,
                "incumbent_count": 1,
                "warm_start_applied": True,
                "warm_start_source": "baseline_plan",
                "search_profile": {
                    "total_wall_clock_sec": 1.5,
                    "first_feasible_sec": 0.1,
                    "incumbent_updates": 1,
                    "evaluator_calls": 2,
                    "avg_evaluator_sec": 0.1,
                    "repair_calls": 1,
                    "avg_repair_sec": 0.1,
                    "exact_repair_calls": 0,
                    "avg_exact_repair_sec": 0.0,
                    "feasible_candidate_ratio": 1.0,
                    "rejected_candidate_ratio": 0.0,
                    "fallback_count": 0,
                },
            },
            "main",
            True,
        ),
        (
            "ga",
            {
                "true_solver_family": "ga",
                "independent_implementation": True,
                "delegates_to": "none",
                "solver_display_name": "GA prototype",
                "solver_maturity": "prototype",
                "candidate_generation_mode": "genetic_population_search",
                "evaluation_mode": "total_cost",
                "eligible_for_main_benchmark": False,
                "eligible_for_appendix_benchmark": True,
                "comparison_note": "Prototype genetic search; appendix benchmark only.",
                "fallback_applied": False,
                "fallback_reason": "none",
                "has_feasible_incumbent": True,
                "incumbent_count": 1,
                "warm_start_applied": True,
                "warm_start_source": "baseline_plan",
                "search_profile": {
                    "total_wall_clock_sec": 1.5,
                    "first_feasible_sec": 0.1,
                    "incumbent_updates": 1,
                    "evaluator_calls": 2,
                    "avg_evaluator_sec": 0.1,
                    "repair_calls": 1,
                    "avg_repair_sec": 0.1,
                    "exact_repair_calls": 0,
                    "avg_exact_repair_sec": 0.0,
                    "feasible_candidate_ratio": 1.0,
                    "rejected_candidate_ratio": 0.0,
                    "fallback_count": 0,
                },
            },
            "appendix",
            False,
        ),
        (
            "abc",
            {
                "true_solver_family": "abc",
                "independent_implementation": True,
                "delegates_to": "none",
                "solver_display_name": "ABC prototype",
                "solver_maturity": "prototype",
                "candidate_generation_mode": "bee_colony_search",
                "evaluation_mode": "total_cost",
                "eligible_for_main_benchmark": False,
                "eligible_for_appendix_benchmark": True,
                "comparison_note": "Prototype bee-colony search; appendix benchmark only.",
                "fallback_applied": False,
                "fallback_reason": "none",
                "has_feasible_incumbent": True,
                "incumbent_count": 1,
                "warm_start_applied": True,
                "warm_start_source": "baseline_plan",
                "search_profile": {
                    "total_wall_clock_sec": 1.5,
                    "first_feasible_sec": 0.1,
                    "incumbent_updates": 1,
                    "evaluator_calls": 2,
                    "avg_evaluator_sec": 0.1,
                    "repair_calls": 1,
                    "avg_repair_sec": 0.1,
                    "exact_repair_calls": 0,
                    "avg_exact_repair_sec": 0.0,
                    "feasible_candidate_ratio": 1.0,
                    "rejected_candidate_ratio": 0.0,
                    "fallback_count": 0,
                },
            },
            "appendix",
            False,
        ),
        (
            "mode_hybrid",
            {
                "true_solver_family": "milp_seeded_alns",
                "independent_implementation": True,
                "delegates_to": "alns",
                "solver_display_name": "MILPSeededALNS",
                "solver_maturity": "prototype",
                "candidate_generation_mode": "milp_seeded_alns",
                "evaluation_mode": "total_cost",
                "eligible_for_main_benchmark": False,
                "eligible_for_appendix_benchmark": True,
                "comparison_note": "MILP-seeded ALNS wrapper; appendix benchmark only.",
                "fallback_applied": False,
                "fallback_reason": "none",
                "has_feasible_incumbent": True,
                "incumbent_count": 1,
                "warm_start_applied": True,
                "warm_start_source": "milp_seed",
                "search_profile": {
                    "total_wall_clock_sec": 1.5,
                    "first_feasible_sec": 0.1,
                    "incumbent_updates": 1,
                    "evaluator_calls": 2,
                    "avg_evaluator_sec": 0.1,
                    "repair_calls": 1,
                    "avg_repair_sec": 0.1,
                    "exact_repair_calls": 0,
                    "avg_exact_repair_sec": 0.0,
                    "feasible_candidate_ratio": 1.0,
                    "rejected_candidate_ratio": 0.0,
                    "fallback_count": 0,
                },
            },
            "appendix",
            False,
        ),
    ]

    for mode, solver_metadata, expected_tier, expected_counts in cases:
        row = _build_row(
            mode_label=mode,
            result_payload=_payload(solver_metadata=solver_metadata),
            wall_clock_seconds=1.5,
            result_json_path=Path(f"{mode}.json"),
        )

        assert row["benchmark_tier"] == expected_tier
        assert row["counts_for_comparison"] is expected_counts
        assert row["eligible_for_main_benchmark"] is bool(solver_metadata["eligible_for_main_benchmark"])
        assert row["eligible_for_appendix_benchmark"] is bool(solver_metadata["eligible_for_appendix_benchmark"])
