export const AppErrorCode = {
  SEED_DATASET_REQUIRED: "SEED_DATASET_REQUIRED",
  BUILT_DATASET_REQUIRED: "BUILT_DATASET_REQUIRED",
  DATASET_INTEGRITY_ERROR: "DATASET_INTEGRITY_ERROR",
  MISSING_ARTIFACT: "MISSING_ARTIFACT",
  SCHEMA_VALIDATION_ERROR: "SCHEMA_VALIDATION_ERROR",

  SCENARIO_NOT_FOUND: "SCENARIO_NOT_FOUND",
  SCENARIO_INCOMPLETE: "SCENARIO_INCOMPLETE",
  SCENARIO_VERSION_MISMATCH: "SCENARIO_VERSION_MISMATCH",

  SOLVER_NOT_AVAILABLE: "SOLVER_NOT_AVAILABLE",
  EXECUTION_IN_PROGRESS: "EXECUTION_IN_PROGRESS",
  ENDPOINT_RETIRED: "ENDPOINT_RETIRED",

  ARTIFACT_MANIFEST_MISSING: "ARTIFACT_MANIFEST_MISSING",
  ARTIFACT_MANIFEST_INVALID: "ARTIFACT_MANIFEST_INVALID",
  MANIFEST_SCHEMA_VERSION_UNSUPPORTED: "MANIFEST_SCHEMA_VERSION_UNSUPPORTED",
  DATASET_VERSION_MISMATCH: "DATASET_VERSION_MISMATCH",
  RUNTIME_VERSION_TOO_OLD: "RUNTIME_VERSION_TOO_OLD",
  ARTIFACT_MISSING: "ARTIFACT_MISSING",
  ARTIFACT_HASH_MISMATCH: "ARTIFACT_HASH_MISMATCH",
} as const;

export type AppErrorCode = (typeof AppErrorCode)[keyof typeof AppErrorCode];

export interface ApiError {
  error: AppErrorCode | string;
  message: string;
  [key: string]: unknown;
}
