// ── Domain re-exports ─────────────────────────────────────────
export type {
  Scenario,
  ScenarioOverlay,
  ScenarioStatus,
  SolverMode,
  FleetConfig,
  ChargingConfig,
  CostConfig,
  SolverConfig,
  TimeOfUseBand,
  ResearchDatasetStatus,
  HHMMTime,
  MinutesFromMidnight,
  // Master data
  Depot,
  Vehicle,
  VehicleTemplate,
  VehiclePowerType,
  Route,
  RouteResolvedStop,
  RouteLinkStatus,
  RouteServiceSummary,
  RouteLinkState,
  RouteVariantType,
  RouteCanonicalDirection,
  RouteFamilySummary,
  RouteFamilyDetail,
  Stop,
  Trip,
  TimetableRow,
  DepotRoutePermission,
  DepotRouteFamilyPermission,
  VehicleRoutePermission,
  VehicleRouteFamilyPermission,
  // Rules
  DeadheadRule,
  TurnaroundRule,
  // Graph
  ConnectionArc,
  ConnectionGraph,
  FeasibilityReason,
  // Duties
  DutyLeg,
  VehicleBlock,
  VehicleDuty,
  DispatchPlanResponse,
  DutyValidationResult,
  DispatchScope,
  // Simulation config
  SimulationConfig,
  TouPriceSlot,
  // Results
  SimulationResult,
  EnergyRecord,
  SocTracePoint,
  OptimizationResult,
  ChargingSlot,
  CostBreakdown,
  // Jobs
  Job,
  JobStatus,
  RunCapabilities,
  // Derived
  DepotSummary,
  RouteSummary,
} from "./domain";

export type { ApiError as AppApiError, AppErrorCode } from "./errors";
export { AppErrorCode as APP_ERROR_CODE } from "./errors";

// ── API DTO re-exports ────────────────────────────────────────
export type {
  ApiListResponse,
  ApiError,
  // Scenario
  ScenarioListResponse,
  ScenarioDetailResponse,
  CreateScenarioRequest,
  UpdateScenarioRequest,
  ResearchDatasetsResponse,
  AppDataStatusResponse,
  AppStateResponse,
  // Depots
  DepotsResponse,
  DepotDetailResponse,
  CreateDepotRequest,
  UpdateDepotRequest,
  // Vehicles
  VehiclesResponse,
  VehicleDetailResponse,
  CreateVehicleRequest,
  CreateVehicleBatchRequest,
  DuplicateVehicleBatchRequest,
  UpdateVehicleRequest,
  VehicleTemplatesResponse,
  VehicleTemplateDetailResponse,
  CreateVehicleTemplateRequest,
  UpdateVehicleTemplateRequest,
  // Routes
  RoutesResponse,
  RouteFamiliesResponse,
  RouteFamilyDetailResponse,
  RouteDetailResponse,
  CreateRouteRequest,
  UpdateRouteRequest,
  ImportOdptRoutesRequest,
  ImportOdptRoutesResponse,
  ImportGtfsRoutesRequest,
  ImportGtfsRoutesResponse,
  StopsResponse,
  StopDetailResponse,
  ImportOdptStopsRequest,
  ImportOdptStopsResponse,
  ImportGtfsStopsRequest,
  ImportGtfsStopsResponse,
  // Timetable / Trips
  TimetableResponse,
  TimetableSummaryResponse,
  TimetableSummaryItem,
  TimetableServiceSummary,
  TimetableRouteSummary,
  UpdateTimetableRequest,
  ImportOdptTimetableRequest,
  ImportOdptTimetableResponse,
  ImportGtfsTimetableRequest,
  ImportGtfsTimetableResponse,
  ImportOdptStopTimetableRequest,
  ImportOdptStopTimetableResponse,
  ImportGtfsStopTimetableRequest,
  ImportGtfsStopTimetableResponse,
  StopTimetablesResponse,
  StopTimetableSummaryResponse,
  StopTimetableSummaryItem,
  StopTimetableServiceSummary,
  StopTimetableStopSummary,
  ImportCsvRequest,
  ExportCsvResponse,
  TripsResponse,
  BuildTripsRequest,
  // Calendar
  CalendarResponse,
  CalendarDatesResponse,
  UpdateCalendarRequest,
  UpsertCalendarEntryRequest,
  UpdateCalendarDatesRequest,
  UpsertCalendarDateRequest,
  // Permissions
  DepotRoutePermissionsResponse,
  DepotRouteFamilyPermissionsResponse,
  VehicleRoutePermissionsResponse,
  VehicleRouteFamilyPermissionsResponse,
  UpdateDepotRoutePermissionsRequest,
  UpdateDepotRouteFamilyPermissionsRequest,
  UpdateVehicleRoutePermissionsRequest,
  UpdateVehicleRouteFamilyPermissionsRequest,
  // Rules
  DeadheadRulesResponse,
  TurnaroundRulesResponse,
  // Graph
  TripsSummaryResponse,
  GraphResponse,
  GraphSummaryResponse,
  GraphArcsResponse,
  BuildGraphRequest,
  // Duties
  BlocksResponse,
  BuildBlocksRequest,
  DutiesResponse,
  DutiesSummaryResponse,
  DutyValidationResponse,
  GenerateDutiesRequest,
  DispatchPlanArtifactResponse,
  BuildDispatchPlanRequest,
  // Simulation
  SimulationResultResponse,
  SimulationConfigResponse,
  SimulationCapabilitiesResponse,
  DispatchScopeResponse,
  UpdateDispatchScopeRequest,
  RunSimulationRequest,
  // Optimization
  OptimizationResultResponse,
  OptimizationCapabilitiesResponse,
  ReoptimizeRequest,
  RunOptimizationRequest,
  // Jobs
  JobResponse,
} from "./api";
