import fs from 'node:fs/promises';
import {pathToFileURL} from 'node:url';
const build=process.argv[2], final=process.argv[3];
const skill='C:/Users/RTDS_admin/.codex/plugins/cache/openai-primary-runtime/presentations/26.930.11008/skills/presentations';
const runtime='C:/Users/RTDS_admin/.cache/codex-runtimes/codex-primary-runtime/dependencies';
process.env.RUNTIME_NODE_MODULES=runtime+'/node/node_modules';
const {finalizePresentation}=await import(pathToFileURL(skill+'/container_tools/artifact_tool_utils.mjs').href);
const d=JSON.parse(await fs.readFile(build+'/data.json','utf8'));
const inventory=JSON.parse(await fs.readFile(build+'/revision_inventory.json','utf8'));
await finalizePresentation({workspaceDir:'C:/master-course',candidatePath:build+'/aligned_candidate.pptx',finalPath:final,explicitTotalSlideCount:44,requiredNativeTableOwnerSlides:inventory.requiredNativeTableOwnerSlides,requiredNativeChartOwnerSlides:inventory.requiredNativeChartOwnerSlides,materializeLiteralChartWorkbooks:false,pythonExecutable:runtime+'/python/python.exe',integrityValidatorPath:skill+'/container_tools/inspect_presentation_package_integrity.py',layoutValidatorPath:skill+'/container_tools/inspect_presentation_layout_geometry.py',layoutArgs:['--expected-slide-size-emu','12192000,6858000',...inventory.requiredNativeTableOwnerSlides.flatMap(i=>['--require-native-table-slide',String(i)])],fontPolicy:{basis:'reference',families:['Noto Sans JP'],referencePath:d.source,referenceSha256:d.source_sha256},verifyArtifactToolImport:true,receiptPath:build+'/verified_final_validation.json'});
console.log('Final 44-slide presentation validated');
