import type { Field } from "./components/Fields";
const number = (key: string, label: string, max?: number): Field => ({
  key,
  label,
  kind: "number",
  min: 0,
  max,
});
const boolean = (key: string, label: string): Field => ({
  key,
  label,
  kind: "boolean",
});
export const vehicleFields: Field[] = [
  { key: "depotId", label: "所属営業所", kind: "select", required: true },
  {
    key: "type",
    label: "動力",
    kind: "select",
    options: ["BEV", "ICE"],
    required: true,
  },
  { key: "modelName", label: "車両モデル名" },
  { key: "modelCode", label: "モデルコード" },
  boolean("enabled", "この車両を使用する"),
  number("batteryKwh", "電池容量（kWh）"),
  number("chargePowerKw", "最大充電電力（kW）"),
  number("energyConsumption", "エネルギー消費原単位（BEV:kWh/km・ICE:L/km）"),
  number("initialSoc", "初期SOC（0〜1）", 1),
  number("minSoc", "SOC下限（0〜1）", 1),
  number("maxSoc", "SOC上限（0〜1）", 1),
  number("fuelTankL", "燃料タンク（L）"),
  number("fuelEfficiencyKmPerL", "燃費（km/L）"),
  number("capacityPassengers", "定員（人）"),
  number("acquisitionCost", "購入費（円）"),
  number("co2EmissionGPerKm", "排出係数（g-CO₂/km）"),
  number("co2EmissionKgPerL", "排出係数（kg-CO₂/L）"),
  number("curbWeightKg", "車両重量（kg）"),
  number("grossVehicleWeightKg", "総重量（kg）"),
  number("engineDisplacementL", "排気量（L）"),
  number("maxTorqueNm", "最大トルク（Nm）"),
  number("maxPowerKw", "最大出力（kW）"),
];
export const depotFields: Field[] = [
  { key: "name", label: "営業所名", required: true },
  { key: "location", label: "所在地" },
  { key: "lat", label: "緯度", kind: "number", min: -90, max: 90 },
  { key: "lon", label: "経度", kind: "number", min: -180, max: 180 },
  number("normalChargerCount", "普通充電器数"),
  number("normalChargerPowerKw", "普通充電器1基の電力（kW）"),
  number("fastChargerCount", "急速充電器数"),
  number("fastChargerPowerKw", "急速充電器1基の電力（kW）"),
  number("depotAreaM2", "営業所面積（m²）"),
  number("parkingCapacity", "駐車容量（台）"),
  boolean("hasFuelFacility", "給油設備あり"),
  boolean("overnightCharging", "夜間充電可"),
  { key: "notes", label: "メモ" },
];
export const routeFields: Field[] = [
  { key: "name", label: "路線名", required: true },
  { key: "startStop", label: "起点" },
  { key: "endStop", label: "終点" },
  number("distanceKm", "距離（km）"),
  number("durationMin", "所要時間（分）"),
  boolean("enabled", "使用する"),
  { key: "routeFamilyCode", label: "系統コード" },
  { key: "routeFamilyLabel", label: "系統名" },
  { key: "routeSeriesCode", label: "系統シリーズ" },
  { key: "depotId", label: "営業所", kind: "select" },
  {
    key: "routeVariantTypeManual",
    label: "運行パターン",
    kind: "select",
    options: [
      "main",
      "main_outbound",
      "main_inbound",
      "short_turn",
      "branch",
      "depot_out",
      "depot_in",
      "unknown",
    ],
  },
  {
    key: "canonicalDirectionManual",
    label: "方向",
    kind: "select",
    options: ["outbound", "inbound", "circular", "unknown"],
  },
  boolean("isPrimaryVariant", "代表パターン"),
];
export const energyFields: Field[] = [
  { key: "depot_id", label: "営業所", kind: "select", required: true },
  boolean("pv_enabled", "PVを使用する"),
  boolean("pv_capacity_kw_manual_override", "PV容量を直接指定する"),
  number("depot_area_m2", "PV算定用の営業所面積（m²）"),
  number("usable_area_ratio", "PVに利用できる面積の比率（0〜1）", 1),
  number("panel_power_density_kw_m2", "パネルの出力密度（kW/m²）"),
  boolean("bess_enabled", "BESSを使用する"),
  number("pv_capacity_kw", "PV設備容量（kW）"),
  number("bess_energy_kwh", "BESS容量（kWh）"),
  number("bess_power_kw", "BESS充放電電力（kW）"),
  number("bess_initial_soc_kwh", "BESS初期残量（kWh）"),
  number("bess_soc_min_kwh", "BESS下限（kWh）"),
  number("bess_soc_max_kwh", "BESS上限（kWh）"),
  {
    key: "bess_terminal_soc_policy",
    label: "期間末の残量",
    kind: "select",
    options: [
      ["minimum_only", "下限以上なら自由"],
      ["return_to_initial", "初期残量に戻す"],
      ["fixed_target", "目標残量を指定する"],
    ],
  },
  {
    key: "bess_balance_period",
    label: "残量を評価する期間",
    kind: "select",
    options: [
      ["evaluation_period", "計画期間全体"],
      ["daily", "日ごと"],
    ],
  },
  number("bess_terminal_soc_min_kwh", "期間末下限（kWh）"),
  number("bess_terminal_soc_target_kwh", "期間末目標（kWh）"),
  number(
    "bess_terminal_soc_deviation_penalty_yen_per_kwh",
    "目標逸脱ペナルティ（円/kWh）",
  ),
  number("bess_charge_efficiency", "充電効率（0〜1）", 1),
  number("bess_discharge_efficiency", "放電効率（0〜1）", 1),
  number("bess_cycle_cost_yen_per_kwh", "充放電費用（円/kWh）"),
  boolean("allow_pv_to_bess", "PVからBESSへ充電"),
  boolean("allow_grid_to_bess", "系統電力からBESSへ充電"),
  boolean("allow_bess_to_bus", "BESSから車両へ給電"),
  {
    key: "grid_to_bess_price_mode",
    label: "系統からの充電条件",
    kind: "select",
    options: [
      ["tou", "時間帯別料金"],
      ["threshold", "単価の上限"],
      ["disabled", "充電しない"],
    ],
  },
  number(
    "grid_to_bess_price_threshold_yen_per_kwh",
    "充電単価の上限（円/kWh）",
  ),
  {
    key: "grid_to_bess_allowed_slot_indices",
    label: "充電可能な時間枠",
    kind: "json",
  },
  {
    key: "bess_priority_mode",
    label: "BESSの運用方針",
    kind: "select",
    options: [
      ["cost_driven", "費用を重視"],
      ["pv_self_consumption", "PV自家消費を重視"],
      ["peak_shaving", "ピーク抑制を重視"],
    ],
  },
];
