import type { Field } from "./components/Fields";

const num = (key: string, label: string, min = 0, max?: number): Field => ({
  key,
  label,
  kind: "number",
  min,
  max,
});
const bool = (key: string, label: string, hint?: string): Field => ({
  key,
  label,
  kind: "boolean",
  hint,
});
const select = (
  key: string,
  label: string,
  options: Field["options"],
): Field => ({ key, label, kind: "select", options });
export const settingGroups: {
  id: string;
  label: string;
  description: string;
  fields: Field[];
}[] = [
  {
    id: "operation",
    label: "運行条件",
    description: "対象便の扱いと、便と便をつなぐ条件を設定します。",
    fields: [
      select("dayType", "運行日区分", [
        ["WEEKDAY", "平日"],
        ["SAT", "土曜"],
        ["SUN_HOL", "日曜・祝日"],
      ]),
      { key: "serviceDate", label: "開始日", kind: "date" },
      num("planningDays", "対象日数", 1, 7),
      {
        ...select("timeStepMin", "時間刻み（分）", ["5", "15", "30", "60"]),
        numericOptions: true,
      },
      bool("includeShortTurn", "区間便を含める"),
      bool("includeDepotMoves", "入出庫便を含める"),
      bool("includeDeadhead", "回送を含める"),
      bool("fixedRouteBandMode", "系統ごとの運用を固定する"),
      bool("allowIntraDepotRouteSwap", "同じ営業所内で系統を交換できる"),
      bool("allowInterDepotSwap", "営業所間の交換を許可する"),
      num("deadheadSpeedKmh", "回送の基準速度（km/h）", 1),
      num("defaultTurnaroundMin", "基本折返し時間（分）"),
      num("turnaroundBufferMin", "折返しの追加余裕（分）"),
      bool("operationTimeWindowEnabled", "運用時間帯を指定する"),
      { key: "startTime", label: "運用開始（HH:MM）" },
      { key: "endTime", label: "運用終了（HH:MM、24時以降可）" },
    ],
  },
  {
    id: "energy",
    label: "SOC・燃料",
    description:
      "車両の初期状態、SOCと燃料の上下限、充電セッションを設定します。BESSは「営業所設備」で編集します。",
    fields: [
      num("initialSoc", "車両の初期SOC（比率0〜1）", 0, 1),
      num("socMin", "車両SOC下限（比率0〜1）", 0, 1),
      num("socMax", "車両SOC上限（比率0〜1）", 0, 1),
      num("finalSocFloorPercent", "車両の期間末SOC下限（%）", 0, 100),
      num("finalSocTargetPercent", "車両の期間末SOC目標（%）", 0, 100),
      num("finalSocTargetTolerancePercent", "目標の許容幅（ポイント）", 0, 100),
      num("initialIceFuelPercent", "ICE初期燃料（%）", 0, 100),
      num("minIceFuelPercent", "ICE燃料下限（%）", 0, 100),
      num("maxIceFuelPercent", "ICE燃料上限（%）", 0, 100),
      num("defaultIceTankCapacityL", "標準燃料タンク（L）"),
      select("chargingPowerModel", "充電電力モデル", [
        ["constant_power_v0", "一定電力"],
        ["piecewise_soc_taper_v1", "SOCに応じて充電電力を抑制"],
      ]),
      num("chargeSetupMinutes", "充電準備（分）"),
      num("chargeTeardownMinutes", "充電終了処理（分）"),
      num("minimumChargeSessionMinutes", "最小充電時間（分）"),
      select("tripEnergyModel", "走行エネルギーモデル", [
        ["distance_average_v0", "距離平均"],
        ["literature_proxy_v1", "文献に基づく代理モデル"],
      ]),
      num("tripEnergySensitivityScale", "走行エネルギー倍率"),
      num("bevTripEnergySensitivityScale", "BEV電力消費倍率"),
      num("iceTripFuelSensitivityScale", "ICE燃料消費倍率"),
    ],
  },
  {
    id: "cost",
    label: "料金・CO₂",
    description: "購入電力、需要料金、燃料、資産費用を区別して設定します。",
    fields: [
      num("gridFlatPricePerKwh", "電力単価（円/kWh）"),
      num("gridSellPricePerKwh", "売電単価（円/kWh）"),
      num("demandChargeCostPerKw", "需要料金単価（円/kW）"),
      num("dieselPricePerL", "軽油単価（円/L）"),
      num("depotPowerLimitKw", "営業所の受電上限（kW）"),
      num("vehicleUsageCostJpyPerUsedBus", "使用車両1台あたりの費用（円）"),
      select("vehicleUsageCostSemantics", "車両費用の意味", [
        ["unclassified", "未分類"],
        ["fixed_vehicle_day_cost", "車両の日次固定費"],
        ["driver_cost_proxy", "運転者費用の代理"],
        ["provisional_sensitivity", "仮定値による感度分析"],
      ]),
      num("pvMarginalChargeCostYenPerKwh", "PV利用単価（円/kWh）"),
      num("pvCurtailPenaltyYenPerKwh", "PV抑制ペナルティ（円/kWh）"),
      num("gridCo2KgPerKwh", "電力の排出係数（kg-CO₂/kWh）"),
      num("iceCo2KgPerL", "軽油の排出係数（kg-CO₂/L）"),
      num("co2PricePerKg", "CO₂価格（円/kg）"),
      num("co2EmissionsCapKg", "CO₂排出量上限（kg、未指定可）"),
      { key: "co2PriceSource", label: "CO₂価格の出典" },
      { key: "co2ReferenceDate", label: "CO₂価格の参照日", kind: "date" },
    ],
  },
  {
    id: "solver",
    label: "ソルバー",
    description:
      "手法と計算予算を設定します。計算終了と最適性の達成は別に確認します。",
    fields: [
      select("solverMode", "最適化手法", [
        ["phase3_two_stage", "Phase 3 · 二段階"],
        ["phase4_integrated", "Phase 4 · 統合"],
        ["mode_milp_only", "MILP"],
        ["mode_alns_only", "ALNS"],
        ["mode_hybrid", "Hybrid"],
      ]),
      num("timeLimitSeconds", "計算時間上限（秒）", 1),
      num("mipGap", "目標MIP gap（比率）", 0, 1),
      num("randomSeed", "乱数seed"),
      num("stage1Stage2CandidateLimit", "二段階候補数", 1, 50),
      num("stage1CompositionSearchRadius", "車両構成の探索範囲", 0, 5),
      num("alnsIterations", "ALNS反復回数", 1),
      num("noImprovementLimit", "改善なしの打切り回数", 1),
      num("destroyFraction", "ALNS破壊率", 0.01, 1),
      num("maxStartFragmentsPerVehicle", "車両ごとの始発候補数", 1),
      num("maxEndFragmentsPerVehicle", "車両ごとの終着候補数", 1),
      num("milpMaxSuccessorsPerTrip", "後続候補数の上限（枝刈りあり）", 1),
      bool("stage1BevFrontierEnabled", "BEV台数の候補探索"),
      num("stage1BevFrontierMinCount", "探索BEV台数の下限"),
      num("stage1BevFrontierMaxCount", "探索BEV台数の上限"),
      num(
        "stage1BevFrontierTargetTimeLimitSeconds",
        "候補ごとの計算上限（秒）",
        1,
      ),
    ],
  },
  {
    id: "objective",
    label: "目的・実験",
    description: "費用項目と研究上の比較条件を明示します。",
    fields: [
      {
        key: "objectivePreset",
        label: "目的プリセット識別子",
        hint: "保存済みの目的設定を確認して指定します。",
      },
      { key: "objectiveMode", label: "目的モード" },
      bool("allowPartialService", "未配車を許容する"),
      num("unservedPenalty", "未配車1便あたりのペナルティ"),
      num("degradationWeight", "電池劣化の重み"),
      bool("disableVehicleAcquisitionCost", "車両購入費を除外する"),
      bool("enableVehicleCost", "車両費を計上する"),
      bool("enableDriverCost", "運転者費を計上する"),
      bool("enableOtherCost", "その他費用を計上する"),
      { key: "costComponentFlags", label: "費用項目の個別設定", kind: "json" },
      { key: "objectiveWeights", label: "目的関数の重み", kind: "json" },
      { key: "touPricing", label: "時間帯別料金", kind: "json" },
      bool("integratedActualCostObjective", "統合モデルで実費を目的にする"),
      select("integratedEvUtilizationMode", "BEV活用の追加目的", [
        ["disabled", "追加しない"],
        ["minimum_ice_fuel_lexicographic", "ICE燃料を辞書式で最小化"],
      ]),
      num("integratedActualCostUpperBoundJpy", "実費の上限（円、未指定可）"),
      num(
        "integratedActualCostUpperBoundDeltaRatio",
        "実費上限の許容差（比率）",
        0,
        1,
      ),
      bool("enableVehicleDiagramOutput", "運行ダイヤの出力を有効にする"),
      { key: "experimentMethod", label: "実験方法" },
      { key: "experimentNotes", label: "実験メモ" },
    ],
  },
  {
    id: "weather",
    label: "PV・気象",
    description: "実測PVと予報を区別し、利用するデータと情報時点を指定します。",
    fields: [
      select("weatherMode", "気象入力", [
        "actual_date_profile",
        "solcast_typical_sunny",
        "solcast_typical_cloudy",
        "solcast_typical_rainy",
        "solcast_typical_auto",
        "sunny",
        "cloudy",
        "rainy",
      ]),
      { key: "pvProfileId", label: "PVプロファイル" },
      num("weatherFactorScalar", "気象係数"),
      bool("enableWeatherOperationPolicy", "気象予報を運用に利用する"),
      select("pvInputSemantics", "PV入力の意味", [
        [
          "available_surplus_after_depot_load",
          "営業所負荷を差し引いた利用可能量",
        ],
        [
          "gross_generation_before_depot_load",
          "営業所負荷を差し引く前の発電量",
        ],
      ]),
      { key: "weatherProxyForecastPath", label: "予報JSON" },
      { key: "weatherProxyDailyCsvPath", label: "日別気象CSV" },
      { key: "weatherProxyStationId", label: "観測地点ID" },
      { key: "weatherProxyStationName", label: "観測地点名" },
      { key: "solcastProxyIssueDate", label: "予報の発行日", kind: "date" },
      { key: "solcastTypicalCurvePath", label: "代表PVカーブJSON" },
      select("solcastTypicalWeatherClass", "代表気象区分", [
        "auto",
        "sunny",
        "cloudy",
        "rainy",
      ]),
      bool(
        "allowFixedWeekdayTimetablePvCounterfactual",
        "固定平日時刻表のPV反実仮想を明示する",
      ),
    ],
  },
];
